// Auth
export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const TOGGLE_SCREENS = 'TOGGLE_SCREENS';
export const AUTH_REQ_STARTED = 'AUTH_REQ_STARTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const AUTH_REQ_FAILED = 'AUTH_REQ_FAILED';

// Employee detail
export const EMPLOYEE_FORM_UPDATE = 'EMPLOYEE_FORM_UPDATE';
export const EMPLOYEE_FORM_RESET = 'EMPLOYEE_FORM_RESET';
export const EMPLOYEE_FORM_INIT = 'EMPLOYEE_FORM_INIT';
export const EMPLOYEE_REQ_STARTED = 'EMPLOYEE_REQ_STARTED';
export const EMPLOYEE_REQ_SUCCESS = 'EMPLOYEE_REQ_SUCCESS';
export const EMPLOYEE_REQ_FAILED = 'EMPLOYEE_REQ_FAILED';

// Employee list
export const EMPLOYEES_FETCH_REQ_STARTED = 'EMPLOYEES_FETCH_REQ_STARTED';
export const EMPLOYEES_FETCH_SUCCESS = 'EMPLOYEES_FETCH_SUCCESS';
